### PR TITLE
Radec fix

### PR DESCRIPTION
**Pull request by profxj**
Simple method and script for modifying a KCWI header
to 'fix' the RA/DEC offset.

This PR should be merged only after the pending *montage*
PR.

Also introduces the first test into the Repo.

### CODE REVIEW

**Comment by astronomeara** [comment]
This is an important fix.  I am going to merge the montage now and open a new montage branch for more updates.

**Comment by astronomeara** [comment]
These look good.  Do we yet have a sense if there is always a specific offset from the RA/DEC in the header (i.e. something relative to field center)?  I suspect there is.  I'll ask around.  Otherwise these routines look good to go.

**Comment by profxj** [comment]
Well, the only thing I might have learned is that when you 
went to a non-rotated frame the offset was quite small.

So, the rotation may be most of the issue.  Just a guess.

**Comment by profxj** [comment]
merging.

**Pull request merged**
