### PR TITLE
Extract and Narrow Band

### PR DESCRIPTION
**Pull request by profxj**
- Cleans up the Narrow band image method
- Adds a script
- Now converts wavelengths to vacuum by default
- Input to the NB image is now the rest-frame "line" of interest.
- Adds extraction script and refactors the 5box code a bit

I could also overload that so that you can insert a transition, e.g.
HI1215 which would be parsed by linetools. Let me know

### CODE REVIEW

**Comment by profxj** [comment]
Here are my calls:

`kcwitools_narrow_band data/FRB_montage_flux.fits 3728.5 --z 0.38413 --outfile data/agalaxyB_OII.fits --sub_off`

`kcwitools_extract_spec data/FRB_montage_flux.fits data/FRB_montage_variance.fits 28 23 --square=5 --outfile galaxyA_spec.fits`

**Comment by rongmon** [comment]
> Here are my calls:
> 
> `kcwitools_narrow_band data/FRB_montage_flux.fits 3728.5 --z 0.38413 --outfile data/agalaxyB_OII.fits --sub_off`
This is great. Working. Also updated show_narrowband script to have an optional --del_wave keyword Defines the delta wavelength range for the narrowband


> 
> `kcwitools_extract_spec data/FRB_montage_flux.fits data/FRB_montage_variance.fits 28 23 --square=5 --outfile galaxyA_spec.fits`

This works as well.

 A side note: Is there an option to change the xspectrum1D object's default plotting style (e.g. making default line width =0.5, and doing plot.step instead of plot.plot)?

**Comment by profxj** [comment]
@rongmon -- For the plotting with XSpectrum1D, do you mean the
matplotlib bit, which is  `xspec.plot()`  or the `linetools` GUI which
is a call `xspec.plot(xspec=True)` ?

I guess this is all the cosmetic change in plotting. So would be in the xspec.plot() part of the routine. 
I haven't checked the xspectrum1D object file, are these inputs taken by the xspec object?

**Review by rongmon — APPROVED** [review]
This looks great. I heartily approve.

**Review by astronomeara — COMMENTED** [review]
For narrowband, should we add the potential of selecting by 'ion'?  Main thought is things like [OII], since there the off-band subtraction is potentially best done asymmetrically.  perhaps calling with --ion 'HI' or --ion '[OII]'

**Comment by rongmon** [comment]
I prefer the wavelength option, because it is cleaner. We can add an ion option with an approximate wavelength, so that it can look up the proper rest frame from a setline routine. I have a custom one, but I bet there is one already in linetools or pyigm.

**Comment by astronomeara** [comment]
ok, sounds good.  Now I need to remind myself of the wavelength of [OII] every time :)

**Comment by astronomeara** [comment]
Recommend deleting the extract_1D_spec from spec.py  Not needed.

**Review by astronomeara — APPROVED** [review]

**Comment by profxj** [comment]
I see now the `ion` option would be challenging as many of the 
galaxy lines have spaces in them (a pain for command line input).

Have removed the extra method.

About to merge.

**Comment by profxj** [comment]
ps.  @astronomeara,  use this:

`lt_line -a --llist Galaxy`

and thank me later

**Pull request merged**
