### PR TITLE
Narrowband image

### PR DESCRIPTION
**Pull request by profxj**
- Cleans up the Narrow band image method
- Adds a script
- Now converts wavelengths to vacuum by default

Input to the NB image is now the rest-frame "line" of interest.
I could also overload that so that you can insert a transition, e.g.
HI1215 which would be parsed by `linetools`.  Let me know

### CODE REVIEW

**Comment by profxj** [comment]
Here is an example call to the script:

`kcwitools_narrow_band data/FRB_montage_flux.fits 3728.5 --z 0.3214 --outfile data/agalaxyA_OII.fits --sub_off`

**Comment by rongmon** [comment]
> Here is an example call to the script:
> 
> `kcwitools_narrow_band data/FRB_montage_flux.fits 3728.5 --z 0.3214 --outfile data/agalaxyA_OII.fits --sub_off`

This is working, but it is not in narrowband branch: it is in extract branch. Can I push some minor edits to this script? Want to add del_wave as a callable variable

**Comment by profxj** [comment]
It should work on the narowband branch, so let's keep on it
(i.e have me fix it).  Extract is next. 

And, yes, do make edits to the script but in the narrowband branch. Thanks!

**Comment by profxj** [comment]
closing as I goofed up the push at one stage...

**Pull request closed without merging**
