### PR TITLE
Starting up

### PR DESCRIPTION
**Pull request by profxj**
This PR does a few start up items

- Brings the `kcwitool` codes into the repo
- Begins doc strings
- Enforces Python 3.6
- Adds a simple `setup.py` script
- Adds a first Notebook

### CODE REVIEW

**Comment by rongmon** [comment]
Both the show_narrowband and and show_whitelight routines are working fine. 
But there are too many routines to read in at the beginning.  I think we still need a wrapper file, that can take the fits file name and do either of these functionalities.

**Comment by profxj** [comment]
Not sure I follow, @rongmon 

Do you mean this line is too much overhead?

`hdr, flux = kcwi_io.open_kcwi_cube(data_file)`

**Comment by rongmon** [comment]
Oh no, I meant something like  kwci.show_whitelight(filename), which will be a wrapper around all the commands in the notebook now. That will avoid the hassle of importing io, utils, image and plot, everytime one wants to inspect a data cube.

**Comment by profxj** [comment]
Ah, got it.  Almost done with that.
It will be a command line script (that you could
call internally too if desired).

**Comment by profxj** [comment]
Added a script to show/generate a white light image.  Try it out:

`kcwitools_white_light test.fits --outfile white_light.fits`

**Comment by rongmon** [comment]
> Added a script to show/generate a white light image. Try it out:
> 
> `kcwitools_white_light test.fits --outfile white_light.fits`

This works. Could you please change the backend to matplotlib.use('TkAgg') before doing the plot. That allows me to look at the pixel number in the matplotlib window.

**Review by rongmon — APPROVED** [review]
This works

**Comment by astronomeara** [comment]
Love it.  Very useful.  Next step is a similar tool that drops single pixel or larger apertures down for a quick look.  RB already has a lot of that in place

**Review by astronomeara — COMMENTED** [review]
change tools readme to give X credit on dev.

Cube trim was done brute force on 1 data set.  guessing can do better than 'by eye' chopping.  trim is wavelength dependent, so is aggressive to get it all in one shot.

MUST do a proper review of the skysub routines (cube_skysub, var_skysub) with an eye towards correct variance propagation.  This routine might get used quite frequently (current pipeline is good, but bad for frames w/ only small regions of no flux), so it should be robust.  May wish to incorporate PypeIt routines for sky modeling.  Not sure how to deal w/ sky gradients.

Regarding headers:  should we be removing anything?  Seems dangerous.  Why not just add the keywords that are expected?

**Comment by profxj** [comment]
@astronomeara -- Those are good points.  I should prefer to defer them
to future PR's.  For now, do we need additional changes as regards the
white light images?

**Comment by profxj** [comment]
Oh, and we do have to remove the `NAXIS3` header  cards
for the WCS to work properly in an image viewer (e.g. DS9, ginga).

**Comment by astronomeara** [comment]
ah, didn't appreciate the naxis3 issue.  surprising, since DS9 loads the cubes just fine

**Comment by profxj** [comment]
Right, but does it handle the white-light image just fine?
Ginga barfs

**Comment by profxj** [comment]
merging.

**Pull request merged**
